############################################
# ? CONFIGURACI�N GENERAL DE LA APLICACI�N
############################################
spring.application.name=sistema-autorizaciones

# Puerto del servidor (usa variable de entorno PORT si existe)
server.port=${PORT:8080}


############################################
# ?? CONFIGURACI�N DE BASE DE DATOS MYSQL
############################################
# URL de conexi�n (usa variable de entorno MYSQL_URL si est� definida)
spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3306/autorizaciones_medicas?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Bogota}

# Usuario y contrase�a (variables de entorno para seguridad en AWS)
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:1234}

# Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


############################################
# ?? CONFIGURACI�N JPA / HIBERNATE
############################################
# Actualiza autom�ticamente el esquema de la base de datos
spring.jpa.hibernate.ddl-auto=update

# Muestra las consultas SQL en la consola (�til para desarrollo)
spring.jpa.show-sql=true


# Formato bonito para logs SQL
spring.jpa.properties.hibernate.format_sql=true


############################################
# ? CONFIGURACI�N DE CODIFICACI�N Y TIMEZONE
############################################
spring.jpa.properties.hibernate.jdbc.time_zone=America/Bogota
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
