spring.application.name=demo

# --- Conexión a MySQL ---
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/autorizaciones_medicas?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
server.port=${PORT:8080}
